// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghbrkuptuwvnbzdrqwlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYnJrdXB0dXd2bmJ6ZHJxd2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njc3MjMsImV4cCI6MjA2OTU0MzcyM30.ounv8MqX9mzjIA0fwjec4ZLOIuWYuqdwuEPLC6szdng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});